# Generated by Django 4.2.7 on 2023-12-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0003_alter_trait_created_at'),
        ('pets', '0004_alter_pet_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='traits',
            field=models.ManyToManyField(related_name='pets', to='traits.trait'),
        ),
    ]
